### PR TITLE
add Angular (v2) library detection

### PR DESCRIPTION
**Pull request by rviscomi**
Adapted from https://github.com/StephenFluin/angular-inspector/blob/f85dea2432db7def04bd7d2256d6fc97fcb57828/src/detector.js#L396-L399 by @StephenFluin

### CODE REVIEW

**Comment by rviscomi** [comment]
Fixes https://github.com/johnmichel/Library-Detector-for-Chrome/issues/88

**Comment by StephenFluin** [comment]
There is also a different icon for Angular vs AngularJS

**Comment by rviscomi** [comment]
> There is also a different icon for Angular vs AngularJS

Updated

**Comment by johnmichel** [comment]
Thanks!

**Pull request merged**
