### PR TITLE
Add brewser.js detection

### PR DESCRIPTION
**Pull request by robertpataki**
Please add detection for http://handcraftedldn.github.io/brewser/

### CODE REVIEW

**Comment by johnmichel** [comment]
This looks great aside from the lack of a second test aside from `win.BREWSER`.  If you add another test to ensure of its existence, I'll merge this in.

**Comment by robertpataki** [comment]
Good point @johnmichel, I'll make the required changes and will make a new pull request ASAP.

**Comment by robertpataki** [comment]
All done, I hope it makes sense.

**Comment by johnmichel** [comment]
:+1: LGTM.

I'll make a release containing this later tonight.

**Comment by robertpataki** [comment]
Awesome thanks a bunch!

**Pull request merged**
